name: Auto Assign Issue
  

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  issues: write

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issue to assignee 
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ RonnieWB3 }}
